### ISSUE TITLE
episode 4 semantics

### ISSUE THREAD

**Issue by danesparza** [arschles/go-in-5-minutes#71]
Thanks for your awesome videos and source code!  

So I'm trying to piece together how websockets work in your episode 4 tuturial.  I notice in the `ServeHTTP` implementation for `wsHandler`, there is a line to [defer removing the newly added connection](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L54).  Presumably this is so the server doesn't leak resources.  

What I'm confused about is when (exactly) the deferred statement gets executed in this case.  And does the [sync.WaitGroup](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L55) come into play?

Can you shed some light on that (or point me in the right direction in some docs).  Thanks!

**Comment by danesparza** [comment]
I think perhaps I answered my own question, but I wanted to sanity check it:

`sync.WaitGroup` ([docs here](https://golang.org/pkg/sync/#WaitGroup)) waits for a collection of goroutines to finish.  In this case, we're waiting for 2 go routines to finish:  The connection's [reader](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L19-L28) and [writer](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L30-L38).  

Both the reader and writer [get passed a reference](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L57-L58) to the WaitGroup (so they can each call `wg.Done()` when they're done).  After they have both called done, the execution after `wg.Wait()` [continues](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L59), the websocket connection is closed, and the hub connection is removed.  

Sound right?

**Comment by danesparza** [comment]
Looks like the "barrier pattern" is outlined nicely [in episode 10](http://www.goin5minutes.com/screencast/episode_10_concurrency_the_daily_walk/) -- if anybody is interested in learning more about `sync.WaitGroup`

**Comment by arschles** [comment]
Hey @danesparza - sorry for the delay here. It seems like you answered your own question though! Hopefully I can add some more clarity:

>What I'm confused about is when (exactly) the deferred statement gets executed in this case

It gets executed after the [`wsConn.Close()`](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L60) line gets executed (if there were multiple `defer`s, they'd get executed in stack order, in case you were wondering).

>sync.WaitGroup (docs here) waits for a collection of goroutines to finish. In this case, we're waiting for 2 go routines to finish: The connection's reader and writer.

Exactly!

>Both the reader and writer get passed a reference to the WaitGroup (so they can each call wg.Done() when they're done).

Yup, and remember that if you pass a `sync.WaitGroup` around, it should always be a reference (AKA a pointer). If you run `go vet` on your code, it should warn you if you forget.

>In this case, we're waiting for 2 go routines to finish: The connection's reader and writer.

Yup, and that's why the code calls [`wg.Add(2)`](https://github.com/arschles/go-in-5-minutes/blob/master/episode4/connection.go#L56) above. If there were more, we'd change the `2` in that call

>After they have both called done, the execution after wg.Wait() continues, the websocket connection is closed, and the hub connection is removed. Sound right?

Yep, that's exactly right. Since it's a websocket connection, the expectation is that the reader and writer will stay open for a while while the two people are talking. If either side leaves, then both the reader and writer will eventually return and the WaitGroup will go to `0` and `wg.Wait()` will then return. 

Again, hopefully that helped a little bit more.
